copy /y "MSI Packages\ESME Application MSI\msi\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
copy /y "MSI Packages\Plugins\Environmental Databases\InstallableNAVO\msi\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
copy /y "EXE Packages\ESME Application\msi\*.exe" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
copy /y "EXE Packages\ESME Application and Databases\msi\*.exe" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
copy /y "EXE Packages\ESME Databases\msi\*.exe" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
rem copy /y "MSI Packages\ESME Databases\BST_2.0\bin\x86\Release\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
rem copy /y "MSI Packages\ESME Databases\DBDB-V_5.4\bin\x86\Release\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
rem copy /y "MSI Packages\ESME Databases\GDEM-V_3.0\bin\x86\Release\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
rem copy /y "MSI Packages\ESME Databases\SMGC_2.0_Minimal\bin\x86\Release\*.msi" "\\earlab.bu.edu\c$\Inetpub\wwwroot\ESME\download"
