//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 3MBS.rc
//
#define IDC_MYICON                      2
#define IDC_BUTTON_OUTPUTFOLDER         3
#define IDC_MYICON2                     3
#define ID_BUTTON_REFRESH               4
#define IDD_MY3MBS_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDC_MY3MBS                      109
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        129
#define IDD_DIALOG_OUTPUT_CONFIG        130
#define IDD_SPECIES_BUILDER             131
#define IDR_MENU_STANDARD               132
#define IDD_BETHYMETRY                  133
#define IDD_ADD_ANIMAT                  135
#define IDD_POPULATE_MODEL_ADD_ANIMAT   135
#define IDD_TIMEOFDAY                   136
#define IDD_DURATION                    137
#define IDB_BITMAP1                     143
#define IDD_DIALOG_TXT_MESSAGE          144
#define IDB_BITMAP2                     150
#define IDB_BITMAP3                     151
#define IDD_POPULATE_MODEL              153
#define IDD_DIALOG_JUNK                 154
#define IDD_POPULATE_MODEL_ADD_MULTIPLE_ANIMATS 155
#define IDD_ENTER_QUANTITY              156
#define IDD_POPULATE_MODEL_ADD_POD      157
#define IDD_POPMDL_ADD_ANIMAT_OLD       158
#define IDD_POPMDL_ADD_N_ANIMATS_OLD    159
#define IDD_POPMDL_ADD_POD_OLD          160
#define IDD_ENTER_BEHAV_NAME            161
#define IDB_BITMAP4                     168
#define IDD_DIALOG_VIEWBATHY            170
#define IDD_DIALOG_MATRIXVECTORMATRXELEMENT 174
#define IDD_DIALOG_2MATRICES1VECTOR     175
#define IDD_DIALOG_1MATRIX1ELEMENT      176
#define IDD_DIALOG_1MATRIX1ELEMENT1VECTOR 177
#define IDD_BINOUTPUT_EXAMINE           180
#define IDD_DIALOG_DEFAULT_PARAMS       182
#define IDI_ICON_NEWMAINICON            184
#define IDD_DIALOG_LIMIT_OUTPUT_INTRVL  186
#define IDD_DIALOG_PDF_SEEDING_METHOD   187
#define IDC_LIST_SPECIES                1002
#define IDC_STATIC_SCENARIO_FILE        1003
#define IDC_LIST_PODS                   1003
#define IDC_BATHYMETRY_FILE             1004
#define IDC_TIMEOFDAY                   1005
#define IDC_LIST_ENVDAT                 1005
#define IDC_DURATION                    1006
#define ID_RUN_SIMULATION               1007
#define ID_EXIT                         1008
#define IDC_CHECK_VAR1                  1009
#define ID_BUTTON_CONFIG_OUTPUT         1009
#define IDC_BROWSE                      1010
#define IDC_BROWSER                     1010
#define IDC_STATIC_TIME_OF_DAT_MSG      1011
#define IDC_STATIC_BATHYMETRY_MSG       1012
#define IDC_STATIC_SPECIES_MSG          1013
#define IDC_STATIC_DURATION_MSG         1014
#define IDC_CHECK_VAR2                  1015
#define IDC_CHECK_VAR3                  1016
#define IDC_CHECK_VAR4                  1017
#define IDC_CHECK_VAR5                  1018
#define IDC_CHECK_VAR6                  1019
#define IDC_RADIO_DIVEDEPTH1            1022
#define IDC_RADIO_DIVEDEPTH2            1023
#define IDC_EDIT_DIVEDEPTH1             1024
#define IDC_RADIO_DIVERATE1             1025
#define IDC_RADIO_DIVERATE2             1026
#define IDC_EDIT_DIVEDEPTH2             1027
#define IDC_EDIT_DIVEDEPTH3             1028
#define IDC_EDIT_DIVEDEPTH_AE_MEAN      1028
#define IDC_EDIT_DIVERATE1              1029
#define IDC_EDIT_DIVERATE2              1030
#define IDC_EDIT_DIVERATE3              1031
#define IDC_STATIC_DIVEDEPTH1           1032
#define IDC_STATIC_DIVEDEPTH2           1033
#define IDC_STATIC_DIVEDEPTH3           1034
#define IDC_EDIT_DIVEDEPTH_AE_STD       1034
#define IDC_RANDOM_SET_SEED_VALUE       1035
#define IDC_NUMBER                      1035
#define IDC_STATIC_DIVERATE1            1035
#define IDC_STATIC_AR2                  1036
#define IDC_EDIT_MIN_LAT                1036
#define IDC_TIMEOFDAY_MM                1036
#define IDC_STATIC_DIVERATE2            1036
#define IDC_ACSTICSRCE_OUTPUTDB         1036
#define IDC_STATIC_AR3                  1037
#define IDC_EDIT_SEC_LAT                1037
#define IDC_TIMEOFDAY_SS                1037
#define IDC_STATIC_DIVERATE3            1037
#define IDC_ACSTICSRCE_DUTYCYCLE        1037
#define IDC_RADIO_DR1                   1038
#define IDC_EDIT_MIN_LON                1038
#define IDC_RADIO_TRAVEL1               1038
#define IDC_ACSTICSRCE_START_ITRNTN     1038
#define IDC_RADIO_DR2                   1039
#define IDC_EDIT_SEC_LON                1039
#define IDC_RADIO_TRAVEL2               1039
#define IDC_ACSTICSRCE_MULTI_ENABLED    1039
#define IDC_EDIT_DR1                    1040
#define IDC_EDIT_TRAVEL1                1040
#define IDC_EDIT_ACSTCSRC_CLKLIST       1040
#define IDC_EDIT_DR2                    1041
#define IDC_EDIT_TRAVEL2                1041
#define IDC_EDIT_ACSTCSRC_ITRNLIST      1041
#define IDC_EDIT_DR3                    1042
#define IDC_EDIT_TRAVEL3                1042
#define IDC_STATIC_DR1                  1043
#define IDC_STATIC_TRAVEL1              1043
#define IDC_STATIC_DR2                  1044
#define IDC_STATIC_TRAVEL2              1044
#define IDC_STATIC_DR3                  1045
#define IDC_STATIC_TRAVEL3              1045
#define IDC_STATIC_DIVEDEPTH_AE_MEAN    1046
#define IDC_STATIC_DIVEDEPTH_AE_STD     1047
#define IDC_EDIT_SI1                    1048
#define IDC_EDIT_SURFACE_INTERVAL1      1048
#define IDC_EDIT_SI2                    1049
#define IDC_EDIT_SURFACE_INTERVAL2      1049
#define IDC_EDIT_SURFACE_INTERVAL_AE_MEAN 1050
#define IDC_RADIO_DC1                   1051
#define IDC_RADIO_DIRECTION_CHANGE1     1051
#define IDC_RADIO_DC2                   1052
#define IDC_RADIO_DIRECTION_CHANGE2     1052
#define IDC_EDIT_DC1                    1053
#define IDC_EDIT_DIRECTION_CHANGE1      1053
#define IDC_EDIT_DC2                    1054
#define IDC_EDIT_DIRECTION_CHANGE2      1054
#define IDC_EDIT_DC3                    1055
#define IDC_EDIT_DIRECTION_CHANGE3      1055
#define IDC_STATIC_DC1                  1056
#define IDC_STATIC_DIRECTION_CHANGE1    1056
#define IDC_STATIC_DC2                  1057
#define IDC_STATIC_DIRECTION_CHANGE2    1057
#define IDC_STATIC_DC3                  1058
#define IDC_STATIC_DIRECTION_CHANGE3    1058
#define IDC_EDIT_RV1                    1059
#define IDC_EDIT_REVERSAL1              1059
#define IDC_EDIT_RV2                    1060
#define IDC_EDIT_REVERSAL2              1060
#define IDC_EDIT_RV3                    1061
#define IDC_EDIT_REVERSAL3              1061
#define IDC_STATIC_RV1                  1062
#define IDC_STATIC_REVERSAL1            1062
#define IDC_STATIC_SURFACE_INTERVAL1    1063
#define IDC_EDIT_TRAVEL_AE_MEAN         1063
#define IDC_STATIC_RV2                  1064
#define IDC_STATIC_REVERSAL2            1064
#define IDC_STATIC_RV3                  1065
#define IDC_STATIC_REVERSAL3            1065
#define IDC_EDIT_AE_STD                 1066
#define IDC_STATIC_SURFACE_INTERVAL1A   1067
#define IDC_EDIT_SURFACE_INTERVAL_AE_STD 1067
#define IDC_EDIT_TRAVEL_AE_COEFF        1068
#define IDC_STATIC_DC1A                 1069
#define IDC_STATIC_DIRECTION_CHANGE1A   1069
#define IDC_EDIT_DC4                    1070
#define IDC_EDIT_DIRECTION_CHANGE4      1070
#define IDC_EDIT_DC5                    1071
#define IDC_EDIT_DIRECTION_CHANGE5      1071
#define IDC_STATIC_DC4                  1072
#define IDC_STATIC_DIRECTION_CHANGE4    1072
#define IDC_STATIC_DC5                  1073
#define IDC_STATIC_DIRECTION_CHANGE5    1073
#define IDC_RADIO_DC3                   1074
#define IDC_RADIO_DIRECTION_CHANGE3     1074
#define IDC_EDIT_RV4                    1075
#define IDC_EDIT_REVERSAL4              1075
#define IDC_EDIT_RV5                    1076
#define IDC_EDIT_REVERSAL5              1076
#define IDC_STATIC_RV4                  1077
#define IDC_STATIC_REVERSAL4            1077
#define IDC_STATIC_RV5                  1078
#define IDC_STATIC_REVERSAL5            1078
#define IDC_RADIO_SUR1                  1079
#define IDC_RADIO_ACENTRATE2            1079
#define IDC_RADIO_SUR2                  1080
#define IDC_RADIO_SURFACE_INTERVAL2     1080
#define IDC_RADIO_ACENTRATE4            1080
#define IDC_RADIO_ACENTRATE1            1080
#define IDC_STATIC_DC2A                 1081
#define IDC_STATIC_DIRECTION_CHANGE2A   1081
#define IDC_STATIC_DC3A                 1082
#define IDC_STATIC_DIRECTION_CHANGE3A   1082
#define IDC_RADIO_RV1                   1083
#define IDC_RADIO_REVERSAL1             1083
#define IDC_RADIO_RV2                   1084
#define IDC_RADIO_REVERSAL2             1084
#define IDC_RADIO_RV3                   1085
#define IDC_RADIO_REVERSAL3             1085
#define IDC_RADIO_RV4                   1086
#define IDC_RADIO_REVERSAL4             1086
#define IDC_RADIO_FB1                   1087
#define IDC_RADIO_FLAT_BOTTOM_DIVE1     1087
#define IDC_RADIO_FB2                   1088
#define IDC_RADIO_FLAT_BOTTOM_DIVE2     1088
#define IDC_STATIC_DC4A                 1089
#define IDC_STATIC_DIRECTION_CHANGE4A   1089
#define IDC_STATIC_DC5A                 1090
#define IDC_STATIC_DIRECTION_CHANGE5A   1090
#define IDC_STATIC_RV1A                 1091
#define IDC_STATIC_REVERSAL1A           1091
#define IDC_STATIC_RV2A                 1092
#define IDC_STATIC_REVERSAL2A           1092
#define IDC_STATIC_RV3A                 1093
#define IDC_STATIC_REVERSAL3A           1093
#define IDC_STATIC_RV4A                 1094
#define IDC_STATIC_REVERSAL4A           1094
#define IDC_STATIC_RV5A                 1095
#define IDC_STATIC_REVERSAL5A           1095
#define IDC_EDIT_ACENTRATE4             1096
#define IDC_EDIT_ACENTRATE1             1096
#define IDC_EDIT_ACENTRATE5             1097
#define IDC_EDIT_ACENTRATE2             1097
#define IDC_EDIT_ACENTRATE6             1098
#define IDC_EDIT_ACENTRATE3             1098
#define IDC_STATIC_ACENTRATE4           1099
#define IDC_STATIC_ACENTRATE1           1099
#define IDC_EDIT_AE_DIVERATE_MEAN       1100
#define IDC_EDIT_AE_DIVERATE_STD        1101
#define IDC_EDIT_AE_DIVERATE_COEFF      1102
#define IDC_STATIC_ACENTRATE5           1103
#define IDC_STATIC_ACENTRATE2           1103
#define IDC_LIST_ANIMAT                 1104
#define IDC_STATIC_ACENTRATE6           1104
#define IDC_STATIC_ACENTRATE3           1104
#define IDC_EDIT_AE_DIVERATE_MEAN2      1105
#define IDC_EDIT_AE_ACCENTRATE_MEAN     1105
#define IDC_EDIT_AE_ACENTRATE_MEAN      1105
#define IDC_BUTTON_ADD_ANIMIT           1106
#define IDC_EDIT_AE_DIVERATE_STD2       1106
#define IDC_EDIT_AE_ACCENTRATE_STD      1106
#define IDC_EDIT_AE_ACENTRATE_STD       1106
#define IDC_BUTTON_DELETE_ANIMIT        1107
#define IDC_EDIT_AE_DIVERATE_COEFF2     1107
#define IDC_EDIT_AE_ACCENTRATE_COEFF    1107
#define IDC_EDIT_AE_ACENTRATE_COEFF     1107
#define IDC_STATIC_ANIMAT_POP           1108
#define IDC_RADIO_SURFINTVL1            1108
#define IDC_RADIO_INDEP                 1109
#define IDC_RADIO_SURFINTVL2            1109
#define IDC_RADIO_GRP                   1110
#define IDC_RADIO_TRAVEL3               1110
#define IDC_RADIO_GRPRAN                1111
#define IDC_RADIO_SURFINTVL_VECTOR3     1111
#define IDC_RADIO_ACENTRATE3            1111
#define IDC_RADIO_GRPNONE               1112
#define IDC_RADIO_DIVERATE3             1112
#define IDC_LIST_GRPBEH                 1113
#define IDC_EDIT_REVERSAL_AE_NUM_MEAN   1113
#define IDC_BUTTON_MODIFY_ANIMIT        1114
#define IDC_EDIT_REVERSAL_AE_NUM_STD    1114
#define IDC_EDIT_REVERSAL_AE_DURATION_MEAN 1115
#define IDC_EDIT_REVERSAL_AE_DURATION_STD 1116
#define IDC_EDIT_REVERSAL_AE_PROBABILITY 1117
#define IDC_RADIO_DIRECTION_VECTOR      1118
#define IDC_RADIO_DIRECTION_CHANGE4     1118
#define IDC_RADIO_SURFINTVL_VECTOR6     1119
#define IDC_RADIO_REVERSAL5             1119
#define IDC_RADIO_DIVEDEPTH3            1120
#define IDC_LIST_ADD_ANI_GRPBEH         1121
#define IDC_RADIO_DIRECTION_CHANGE5     1121
#define IDC_STATIC_TIMEOFDAY            1124
#define IDC_BUTTON_TIME                 1125
#define IDC_BUTTON_BATHYMETRY           1126
#define IDC_BUTTON_DURATION             1127
#define IDC_BUTTON_SPEC_ADD             1128
#define IDC_EDIT_AE_DIRECTION_CHANGE_PERTURBATION 1128
#define IDC_BUTTON_BATHYMETRY_CLEAR     1129
#define IDC_EDIT_AE_DIRECTION_CHANGE_TERM_PROB 1129
#define IDC_BUTTON_BATHYMETRY_TO_TXT_FILE 1130
#define IDC_EDIT_AE_THESHOLD            1130
#define IDC_BUTTON_SPEC_REMOVE          1131
#define IDC_TIMEOFDAY_HH                1131
#define IDC_BUTTON_POPMODEL_POD_ADD2    1131
#define IDC_EDIT_SPE_NAME               1132
#define IDC_BUTTON_ENVDAT_ADD           1132
#define IDC_EDIT_SPEC_COMMENT           1133
#define IDC_BUTTON_ENVDAT_REMOVE        1133
#define IDC_PREEXIST1                   1135
#define IDC_PREEXIST2                   1136
#define IDC_RADIO_EXPOSURE_YES          1137
#define IDC_RADIO_EXPOSURE_NO           1138
#define IDC_PREEXIST3                   1139
#define IDC_BUTTON_BEH_VECTOR           1140
#define IDC_STATIC_OUTPUT               1141
#define IDC_USER_MODEL_CLEAR            1141
#define IDC_USER_MODEL_SAVE_TO_TEXT     1142
#define IDC_PROGRESS1                   1142
#define IDC_SEL_SKIP_USER_MODEL         1143
#define IDC_STATIC_PROGRESS             1143
#define IDC_RANDOM_SEED_RANDOM          1144
#define IDC_RANDOM_SEED_AUTO            1144
#define IDC_SEL_USER_MODEL2             1144
#define IDC_SEL_USER_MODEL              1144
#define IDC_RANDOM_SEED_PRESERVE        1145
#define IDC_RANDOM_SEED_SET             1146
#define IDC_SCENARIO_TO_TXT             1147
#define IDC_BUTTON_DIVEDEPTH_VECTOR     1147
#define IDC_LOAD_SCENARIO               1148
#define IDC_BUTTON_SURFINTVL_VECTOR     1148
#define IDC_SAVE_SCENARIO               1149
#define IDC_BUTTON_TRAVEL_VECTOR        1149
#define IDC_EXTRACT_TEXT_FROM_BIN       1150
#define IDC_BUTTON_DIVERATE_VECTOR      1150
#define IDC_BUTTON_ACENTRATE_VECTOR     1151
#define IDC_BUTTON_REVERSAL_VECTOR      1152
#define IDC_PLAYBACK_FILE               1152
#define IDC_STATIC_TXT_MESS_INSTRUCT    1153
#define IDC_BUTTON_DIRECTION_VECTOR     1153
#define IDC_PLAYBACK_FILE2              1153
#define IDC_BUTTON1                     1154
#define IDC_BUTTON_SET_ACSOURCE_COORD   1154
#define IDC_VIEWBATHYMETRY              1154
#define IDC_BUTTON_DEBUG_ADDPODMEMBER   1154
#define IDC_BUTTON_BIN_EXT_PARTIAL      1154
#define IDC_BUTTON_LOAD_SHAPEFILE       1154
#define IDC_BUTTON_TEXT_EXT_PARTIAL     1155
#define IDC_BUTTON_ENABLESPECFICANIMAT  1155
#define IDC_TESTBUTTON                  1155
#define IDC_BUTTON_DIVEDEPTH_VECTOR2    1156
#define IDC_BUTTON_TEXT_EXT_FULL        1156
#define IDC_BUTTON_POPMODEL_POD_ADDN    1158
#define IDC_BUTTON_POPMODEL_POD_MODIFY  1160
#define IDC_LIST_INDIVIDUAL             1161
#define IDC_LAT_POS                     1162
#define IDC_BUTTON_POPMODEL_POD_REMOVE2 1162
#define IDC_LAT_NEG                     1163
#define IDC_STATIC_ENTER_QUANTITY       1163
#define IDC_LON_POS                     1164
#define IDC_OUTPUT_TEXT                 1164
#define IDC_LON_NEG                     1165
#define IDC_OUTPUT_BINARY               1165
#define IDC_CHECK_AE_TRAVEL             1166
#define IDC_CHECK_AE_DIRECTION          1167
#define IDC_CHECK_AE_DIVING             1168
#define IDC_CHECK_CUMMULATIVE_EXP       1169
#define IDC_STATIC_AE_1                 1170
#define IDC_STATIC_AE_2                 1171
#define IDC_STATIC_AE_3                 1172
#define IDC_STATIC_AE_4                 1173
#define IDC_STATIC_AE_5                 1174
#define IDC_STATIC_AE_6                 1175
#define IDC_STATIC_AE_SI_MEAN           1176
#define IDC_STATIC_AE_DIVERATE_MEAN     1177
#define IDC_STATIC_AE_DIVERATE_STD      1178
#define IDC_STATIC_AE_DIVERATE_COEFF    1179
#define IDC_STATIC_TRAVEL_AE_MEAN       1180
#define IDC_STATIC_TRAVEL_AE_STD        1181
#define IDC_STATIC_TRAVEL_AE_COEFF      1182
#define IDC_STATIC_AE_SI_STD            1183
#define IDC_STATIC_SI_MEAN              1184
#define IDC_STATIC_SI_STD               1185
#define IDC_STATIC_AE_NUM_MEAN1         1186
#define IDC_STATIC_AE_NUM_MEAN2         1187
#define IDC_STATIC_REVERSAL_AE_NUM_STD1 1188
#define IDC_STATIC_REVERSAL_AE_NUM_STD2 1189
#define IDC_STATIC_REVERSAL_AE_DURATION_MEAN1 1190
#define IDC_STATIC_REVERSAL_AE_DURATION_MEAN2 1191
#define IDC_STATIC_REVERSAL_AE_DURATION_STD1 1192
#define IDC_STATIC_REVERSAL_AE_DURATION_STD2 1193
#define IDC_STATIC_REVERSAL_AE_PROBABILITY 1194
#define IDC_STATIC_AE_DIRECTION_CHANGE_PERTURBATION1 1195
#define IDC_STATIC_AE_DIRECTION_CHANGE_PERTURBATION2 1196
#define IDC_STATIC_AE_DIRECTION_CHANGE_TERM_PROB1 1197
#define IDC_STATIC_AE_DIRECTION_CHANGE_TERM_PROB2 1198
#define IDC_STATIC_AE_EXPOSURE_EFFECTS  1199
#define IDC_STATIC_AE_EXP_THRESH        1200
#define IDC_STATIC_AE_LINE1             1201
#define IDC_STATIC_AE_LINE2             1202
#define IDC_STATIC_AE_7                 1203
#define IDC_STATIC_CURRENT_TASK         1204
#define IDC_STATIC_AE_ACCENTRATE_MEAN   1204
#define IDC_STATIC_AE_ACENTRATE_MEAN    1204
#define IDC_STATIC_AE_ACCENTRATE_STD    1205
#define IDC_STATIC_AE_ACENTRATE_STD     1205
#define IDC_LIST_VECTOR_MODEL_BEHAV_NAMES 1206
#define IDC_EDIT_BEH_NAME               1207
#define IDC_STATIC_AE_ACCENTRATE_COEFF  1207
#define IDC_STATIC_AE_ACENTRATE_COEFF   1207
#define IDC_STATIC_AE_LINE3             1208
#define IDC_RADIO_AE_PODRES_STAYPOD     1209
#define IDC_RADIO_AE_PODRES_BREAKUP     1210
#define IDC_RADIO_DISTCALC_LATLO        1211
#define IDC_CHECK_ANIMATBEACHES         1211
#define IDC_RADIO_DISTCALC_PGEOM        1212
#define IDC_RADIO_OUTPUT_TXT_SINGLE     1214
#define IDC_RADIO_OUTPUT_TXT_MULTI      1215
#define IDC_OUTPUT_TXT_ITSPERFILE       1216
#define IDC_STATIC_NUM_ITERATIONS       1217
#define IDC_STATIC_TOT_ANIMALS          1218
#define IDC_STATIC_BINOUT_STOR          1219
#define IDC_STATIC_TXTOUT_STO           1220
#define IDC_STATIC_BINOUT_SPAC          1221
#define IDC_STATIC_TXTOUT_SPAC          1222
#define IDC_STATIC_BINUNIT              1223
#define IDC_STATIC_TXTUNIT              1224
#define IDC_STATIC_NUM_ITERATIONS2      1225
#define IDC_STATIC_NUM_SAVEDSTATES      1225
#define IDC_CHECK_ACSOURCE_ACTIVE       1227
#define IDC_EDIT_ACSOURCE_INTENSITY     1228
#define IDC_LIST_MESSAGES               1233
#define IDC_COMBO1                      1234
#define IDC_STATIC_MATLAB_DETECTED_TXT  1236
#define IDC_STATIC_ESME_DETECTED_TXT    1237
#define IDC_LINK                        1238
#define IDC_STATIC_MATLAB_DETECTED_WINDOW 1239
#define IDC_STATIC_ESME_CONNECTED_WINDOW 1240
#define IDC_STATIC_ABOUT                1241
#define IDC_RADIO1                      1242
#define IDC_RADIO_MOUSE_CLICKING        1242
#define IDC_RADIO_STATEDATAFORMAT_ANIMAT 1242
#define IDC_STATIC_MOUSE_POSITION_LATLON 1243
#define IDC_RADIO_STATEDATAFORMAT_ITERATION 1243
#define IDC_RADIO_BOUNDING_BOX          1244
#define IDC_RADIO_N_ANIMATS_AROUND_CLICK 1245
#define IDC_RADIO_N_ANIMATS_OVERMAP     1246
#define IDC_STATIC_MOUSE_POSITION_DEPTH 1247
#define IDC_RADIO_ANIMATS_BY_DENSITY    1247
#define IDC_STATIC_MOUSE_POSITION_SALINITY 1248
#define IDC_RADIO_POLYGON               1248
#define IDC_STATIC_MOUSE_POSITION_TEMPERATURE 1249
#define IDC_RADIO_POISSONICALLY_ANIMATS_AROUND_CLICK 1249
#define IDC_RADIO_LOAD_SHAPE_FILE       1249
#define IDC_EDIT_NUM_ANIMATS            1256
#define IDC_EDIT_AVE_DIST               1257
#define IDC_EDIT_STD_DIST               1258
#define IDC_RADIO_SEED_INDIVIDUAL       1259
#define IDC_RADIO_ADD_POD               1260
#define IDC_RADIO_SEED_POD              1261
#define IDC_EDIT_DENSITY                1261
#define IDC_EDIT_ENVBITMAP_FOCAL_DIST   1262
#define IDC_LIST_SEL_POP                1263
#define IDC_BUTTON_MANUALLY_POPULATE    1264
#define IDC_EDIT_ENVBITMAP_INIT_PODSIZE 1264
#define IDC_STATIC_POP_LOCATION         1265
#define IDC_STATIC_TASK                 1266
#define IDC_LIST_SPECIES_ENVPOP         1267
#define IDC_STATIC_NUMANIMATS           1268
#define IDC_STATIC_AVEDIST              1269
#define IDC_STATIC_STDEVDIST            1270
#define IDC_STATIC_COORDINATE           1271
#define IDC_STATIC_DENSITY              1271
#define IDC_STATIC_BATHYDEPTH           1272
#define IDC_STATIC_DENSITYCALC          1272
#define IDC_STATIC_SALINITY             1273
#define IDC_STATIC_TEMPERATURE          1274
#define IDC_STATIC_INDIVIDUAL           1275
#define IDC_STATIC_PODS                 1276
#define IDC_BUTTON_ENVDLG_SPEC_ADD      1277
#define IDC_BUTTON_ENVDLG_SPEC_REMOVE   1278
#define IDC_STATIC_SEED_SPECIES         1279
#define IDC_STATIC_SEEDING_METHOD       1280
#define IDC_STATIC_CURSOR               1281
#define IDC_STATIC_ENVBITMAP_FOCAL_DIST 1282
#define IDC_EDIT_MOUSE_POSITION_LATLON  1283
#define IDC_RADIO_PODLEADTYPE_ANIMAT    1284
#define IDC_RADIO_PODLEADTYPE_CENTROID  1285
#define IDC_STATIC_POD_LEADER           1286
#define IDC_EDIT_SURINTVAL_VECTOR       1286
#define IDC_EDIT_BEH_VECTOR             1287
#define IDC_STATIC_ENVBITMAP_INITPODSIZE 1287
#define IDC_EDIT_TRAVEL_VECTOR          1288
#define IDC_BUTTON_ENVDLG_FIRSANIMATACSTSRCE 1288
#define IDC_EDIT_ACENTRATE_VECTOR       1290
#define IDC_BUTTON_PODSIZEDEC           1290
#define IDC_STATIC_VMDIVEDEPTH          1291
#define IDC_BUTTON_ENVDLG_INDIVIDUAL_DELETE 1291
#define IDC_EDIT_DIVERATE_VECTOR        1292
#define IDC_BUTTON_ENVDLG_POD_DELETE    1292
#define IDC_STATIC_VMSI                 1293
#define IDC_BUTTON_ENVDLG_PODMEMBER_DELETE 1293
#define IDC_EDIT_DIVEDEPTHL_VECTOR      1294
#define IDC_BUTTON_PODSIZEINC           1294
#define IDC_EDIT_TRAVEL_VECTOR4         1295
#define IDC_EDIT_DIRECTION_VECTOR       1295
#define IDC_BUTTON_DENSITYDISTRIBUTE    1295
#define IDC_STATIC_VMTRAVEL             1296
#define IDC_BUTTON_TOGGLE_DATPTS        1296
#define IDC_EDIT_REVERSAL_VECTOR        1297
#define IDC_BUTTON_TOGGLE_SLOPEREGIONS  1297
#define IDC_STATIC_VMDESCENT            1298
#define IDC_BUTTON_TOGGLE_EXTRAS        1298
#define IDC_STATIC_VMASCENT             1299
#define IDC_BUTTON_TOGGLE_DATPTS2       1299
#define IDC_STATIC_VMREVERSAL           1300
#define IDC_BUTTON_TOGGLE_SLOPEREGIONS2 1300
#define IDC_STATIC_VMDIRECTION          1301
#define IDC_BUTTON_TOGGLE_EXTRAS2       1301
#define IDC_STATIC_VMBEHAVIOR           1302
#define IDC_BUTTON_TOGGLE_DATPTS3       1302
#define IDC_STATIC_BEHNAMES             1303
#define IDC_BUTTON_TOGGLE_SLOPEREGIONS3 1303
#define IDC_EDIT1                       1304
#define IDC_BUTTON_TOGGLE_EXTRAS3       1304
#define IDC_EDIT2                       1305
#define IDC_EDIT3                       1306
#define IDC_EDIT4                       1307
#define IDC_STATIC_VECTORMDL1           1308
#define IDC_STATIC_VECTORMDL2           1309
#define IDC_STATIC_VECTORMDL3           1310
#define IDC_STATIC_VECTORMDL4           1311
#define IDC_STATIC_MAPHEIGHT            1313
#define IDC_STATIC_MAPWIDTH             1314
#define IDC_STATIC_MAPSURFAREA          1315
#define IDC_STATIC_CURSPOSLAT           1316
#define IDC_STATIC_CURSPOSLON           1317
#define IDC_STATIC_CURSPOSDEPTH         1318
#define IDC_STATIC_CURSPOSSLOPE         1319
#define IDC_STATIC_ANIMATPOPSIZE        1320
#define IDC_STATIC_ANIMATDENSITY        1321
#define IDC_STATIC_MAPHEIGHT2           1322
#define IDC_STATIC_MAPSURFAREA_WATER    1323
#define IDC_CHECK_BATHYMAP              1324
#define IDC_STATIC_MAPSURFAREA_LAND     1324
#define IDC_BUTTON_STATE_MIN            1325
#define IDC_STATIC_CURSPOS_SPE_STIM     1325
#define IDC_STATIC_MOUSE_POSITION       1326
#define IDC_CHECK_SALINITYMAP           1327
#define IDC_STATIC_MAPWIDTH2            1327
#define IDC_CHECK_TEMPMAP               1328
#define IDC_STATIC_MAPSURFAREA3         1328
#define IDC_CHECK_TEMPVALUE             1329
#define IDC_STATIC_MAPSURFAREA_WATER2   1329
#define IDC_CHECK_ANIMATSPEASSOCIATION  1330
#define IDC_STATIC_MAPSURFAREA_LAND2    1330
#define IDC_CHECK_DIVERATE              1331
#define IDC_STATIC_ANIMATPOPSIZE2       1331
#define IDC_STATIC_ANIMATDENSITY2       1332
#define IDC_CHECK_SALINITYVALUE         1333
#define IDC_STATIC_MAPHEIGHT3           1333
#define IDC_CHECK_BEARING               1334
#define IDC_STATIC_MAPWIDTH3            1334
#define IDC_STATIC_MAPSURFAREA4         1335
#define IDC_CHECK_TRAVELRATE            1336
#define IDC_STATIC_MAPSURFAREA_WATER3   1336
#define IDC_CHECK_AECUMTV               1337
#define IDC_STATIC_MAPSURFAREA_LAND3    1337
#define IDC_CHECK_AEINST                1338
#define IDC_CHECK_AEANGLE               1339
#define IDC_CHECK_AETIME                1340
#define IDC_CHECK_BATHYVALUE            1341
#define IDC_CHECK_TARGETDEPTH           1342
#define IDC_CHECK_AESTATS               1343
#define IDC_CHECK_AECOORDSTATE          1344
#define IDC_CHECK_XYRELATIVECOORD       1345
#define IDC_CHECK_XYDISTANCEMETERS      1345
#define IDC_BUTTON_STATE_NONE           1347
#define IDC_BUTTON_STATE_FULL           1348
#define IDC_CHECK_CLOCK                 1349
#define IDC_CHECK_ID                    1350
#define IDC_CHECK_COORD                 1351
#define IDC_CHECK_DEPTH                 1352
#define IDC_CHECK_PACKED                1353
#define IDC_STATIC_ANIMAT_STATE_SIZE    1354
#define IDC_STATIC_TOTAL_ANIMATS        1355
#define IDC_STATIC_STORAGE_PER_ITERATION 1356
#define IDC_STATIC_NUMOUTPUT_ITERATIONS 1357
#define IDC_STATIC_OUTPUT_BUFF_LEN      1358
#define IDC_STATIC_STATE_DATA_FORMAT    1359
#define IDC_STATIC_AVAILMEM             1360
#define IDC_EDIT_SPECIFICANIMAT         1360
#define IDC_STATIC_SPECIFICANIMAT       1361
#define IDC_CHECK_RISK                  1361
#define IDC_STATIC_OUTPUT_BUFF_SIZE     1362
#define IDC_STATIC_STATE_OUTPUTFOLDER   1363
#define IDC_STATIC_SOURCE_STATE_SIZE    1364
#define IDC_BUTTON_MID                  1365
#define IDC_STATIC_ANIMAT_BYTESPERITERATION 1365
#define IDC_BUTTON_SHALLOW              1366
#define IDC_BUTTON_DEEP                 1367
#define IDC_STATIC_SCALE                1368
#define IDC_STATIC_TOTAL_ITERATIONS     1368
#define IDC_STATIC_TOTALBYTESPER_ITERATIONS 1369
#define IDC_STATIC_SLOPE_SCALE          1369
#define IDC_STATIC_RESOLUTION_LAT       1371
#define IDC_STATIC_RESOLUTION_LON       1372
#define IDC_SLIDER1                     1373
#define IDC_STATIC_RESOLUTION_LAT2      1373
#define IDC_VISUAL_RUN_BUTTON           1374
#define IDC_STATIC_ITERATION_CNT        1375
#define IDC_STATIC_RESOLUTION_LON2      1375
#define IDC_STATIC_RESOLUTION_LAT3      1376
#define IDC_STATIC_DEFAULT_VALUES       1377
#define IDC_STATIC_RESOLUTION_LON3      1377
#define IDC_STATIC_DEFAULT_VALUES2      1378
#define IDC_STATIC_PING_COORD_ENABLED   1378
#define IDC_VISUAL_PLAY_BUTTON          1378
#define IDC_STATIC_DEFAULT_VALUES3      1379
#define IDC_STATIC_TEXTX10              1379
#define IDC_VISUAL_RESET_BUTTON         1379
#define IDC_STATIC_POPULANTS_GROUP_BOX  1380
#define IDC_STATIC_SPE_ACSRC            1381
#define IDC_STATIC_SEEDOPTNS_GRPBOX     1382
#define IDC_STATIC_LEADANIMATSETTING_GRPBOX 1383
#define IDC_STATIC_ADJUSTPODSIZE_GRPBOX 1384
#define IDC_STATIC_MAPGROUPBOX          1385
#define IDC_STATIC_ANIMATDENSITYGROUPBOX 1386
#define IDC_STATIC_BATHYBOX             1387
#define IDC_STATIC_MAPGROUPBOX2         1388
#define IDC_STATIC_ANIMATDENSITYGROUPBOX2 1389
#define IDC_STATIC_MAPGROUPBOX3         1390
#define IDC_STATIC_DISPLAYOPTSGROUPBOX  1391
#define IDC_STATIC_DISPLAYOPTSGROUPBOX2 1392
#define IDC_STATIC_DISPLAYOPTSGROUPBOX3 1393
#define IDC_STATIC_CURSORPOS            1394
#define IDC_VIEWOUTPUT_RESULTS          1395
#define IDC_LOAD_BINFILE                1395
#define IDC_VISUAL_INC_BUTTON           1395
#define IDC_CHECK_ENABLE_LIMOUTBYINTERVL 1395
#define IDC_TRACKTOGGLE_BUTTON          1396
#define IDC_EDIT_LIMOUTBYINTERVL_VALUE  1396
#define IDC_VISUAL_DEC_BUTTON           1397
#define IDC_EDIT_LIMOUTBYINTERVL_START  1397
#define IDC_VISUAL_STOP_BUTTON          1398
#define IDC_STATIC_FILENAME             1401
#define IDC_EDIT_LOADSPEFILEFEEDBACK    1408
#define IDC_LIST_STOCK                  1410
#define IDC_STATIC_SPECIES_FILE_NAME    1411
#define IDC_LIST_SEASON                 1412
#define IDC_LIST_STUDY                  1413
#define IDC_STATIC_NUM_POLYGONS         1414
#define IDC_STATIC_EXPADDCNT            1415
#define IDC_STATIC_SPECIES_FILE_NAME2   1416
#define IDC_STATIC_ACTUALCNT            1417
#define IDC_STATIC_NUM_ENTRIES          1418
#define IDC_STATIC_SHAPE_BOUNDS_MIN     1420
#define IDC_STATIC_SHAPE_BOUNDS_MAX     1421
#define IDC_STATIC_SEARCHQUERY          1422
#define IDC_STATIC_SPECIES_FILE_NAME3   1423
#define IDC_BUTTON_PDF_SEED             1424
#define IDC_STATIC_ADD_STATUS           1426
#define IDC_STATIC_POSSIBLESHAPEFILE_HEADER 1427
#define IDC_RADIO2                      1428
#define IDC_RADIO3                      1429
#define IDC_RADIO4                      1430
#define IDC_RADIO5                      1431
#define IDC_RADIO6                      1432
#define IDC_RADIO7                      1433
#define ID_SCENARIO_LOAD                32772
#define ID_SCENARIO_BUILD               32773
#define ID_SPECIES_LOAD                 32774
#define ID_SPECIES_BUILD                32775
#define ID_BATHYMETRY_LOAD              32776
#define ID_BATHYMETRY_BUILD             32777
#define ID_FILE_RUNSIMULATION           32778
#define ID_FILE_RUN_SIMULATION          32779
#define ID_FILE_LOAD_SCENARIO           32780
#define ID_SCENARIO_NEW                 32781
#define ID_SCENARIO_ADDSPECIES          32782
#define ID_FILE_CLOSESCENARIO           32783
#define ID_FILE_CLOSE_SCENARIO          32784
#define ID_SCENARIO_ADDBATHYMETRY       32785
#define ID_FILE_SAVE_SCENARIO           32786
#define ID_FILE_SAVESCENARIOAS          32787
#define ID_FILE_SAVE_SCENARIO_AS        32788
#define ID_FILE_NEW_SCENARIO            32789
#define ID_FILE_ADDSPECIES              32790
#define ID_FILE_ADD_SPECIES             32791
#define ID_SCENARIO_BATHYMETRY          32792
#define ID_FILE_DELETE_SPECIES          32793
#define ID_FILE_CONFIGURESCENARIOOUTPUT 32794
#define ID_FILE_CONFIGURE_OUTPUT        32795
#define ID_SPECIES_OPEN                 32796
#define ID_FILE_BATHYMETRY              32797
#define ID_BATHYMETRY_OPEN              32798
#define ID_STANDARD_FILE_OPEN           32799
#define ID_STANDARD_FILE_SAVE           32800
#define ID_STANDARD_FILE_SAVE_AS        32801
#define ID_SPECIES_NEW                  32802
#define ID_BATHYMETRY_NEW               32803
#define ID_STANDARD_FILE_CLOSE          32804
#define IDM_HELP_INSTRUCTIONS           32805
#define IDM_EXTRACT_TEXT_FROM_BIN       32806
#define ID_FILE_LOADSPECIFICITERATIONSAVEFILE 32807
#define ID_SPECIFICDATAPOINTTIMES_LOADFILE 32808
#define ID_SPECIFICDATAPOINTTIMES_CLEAR 32809
#define ID_Menu                         32810
#define ID_Menu_AUTOGENERATEFILENAME    32811
#define ID_AUTOGENERATEFILENAME         32812
#define ID_Menu32813                    32813
#define IDM_PLAYBACK_DATA_FROM_BIN      32814
#define ID_FILE_LIMITOUTPUT             32815
#define ID_LIMITOUTPUT_PINGCYCLES       32816
#define ID_AUTOTESTS_CATAGORY1          32817
#define ID_CATAGORY1_RUN                32818
#define ID_HELP_DEFAULTPARAMETERS       32819
#define ID_LIMITOUTPUTBY_FIXEDINTERVAL  32820
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1434
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
